:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= The cmake_check configuration file

This document is all you need to know about what's required in your cmake_check configuration file. 
It must be actual JSON, not just a JavaScript object literal. It contains of one JSON object, its
members are described in the following sections.

== crawler
`required, type: object`

The _crawler_ object contains options for the directory traversal during search for CMake files.

=== excludePaths
`optional, type: string[]`

A list of regular expressions that match directories that shall be skipped during traversal.
Some folders like `.git` contain a lot of files but are not relevant for cmake_check, 
excluding them reduces analysis time. Also add directories that contain uninteresting
files and should be excluded from analysis like 3rd party code.

[source,json]
----
"excludePaths":[".git$", ".svn$"]
----

NOTE: TODO describe how to properly escape . and fix example
      describe how to match more segments of a path, os path separator etc.
