:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= The cmake_check configuration file

This document is all you need to know about what's required in your cmake_check configuration file. 
It must be actual JSON, not just a JavaScript object literal. It contains of one JSON object, its
members are described in the following sections.

As a reference, a commented JSON https://github.com/DaelDe/cmake_check/blob/master/res/config.schema.json[schema] exists.

== crawler
`required, type:object`

The _crawler_ object contains options for the directory traversal during search for CMake files.

=== excludePaths
`optional, type:string[]`

A list of regular expressions that match directories that shall be skipped during traversal.
Some folders like `.git` contain a lot of files but are not relevant for cmake_check, 
excluding them reduces analysis time. Also add directories that contain uninteresting
files and should be excluded from analysis like 3rd party code.

[source,json]
----
"excludePaths":[".git$", ".svn$"]
----

NOTE: TODO describe how to properly escape . and fix example
      describe how to match more segments of a path, os path separator etc.

== cRules
`required, type:Rule[]`

The collection of rules that should be applied to CMake files. At least one 
rule is required.

=== Rule
`type:object`

A rule is a logical element that describes a requirement to CMake files (an element
of a coding guideline). A rule consists of any number of checks. The rule is checked
for each input file and passes when all checks pass.
